---

- name: Ensure supported OS for package installs
  ansible.builtin.assert:
    that:
      - "ansible_distribution == 'Debian'"
      - "mailman3_domains is not defined"
    success_msg: "OS and configuration are supported for Mailman 3 installation by package"
    fail_msg: "OS and configuration are not supported for Mailman 3 installation by package, set `mailman3_install_method` to `pip`"

- name: Install Mailman and dependency packages
  ansible.builtin.package:
    name: "{{ mailman3_packages }}"
