---

- name: Include core user creation tasks
  ansible.builtin.include_tasks: user.yml
  when: mailman3_create_core_user
  vars:
    _mailman3_user: "{{ mailman3_core_user }}"

- name: Include group discovery tasks
  ansible.builtin.import_tasks: group_discovery.yml

- name: Include installation tasks
  ansible.builtin.import_tasks: "install_{{ mailman3_install_method }}.yml"

- name: Include configuration tasks
  ansible.builtin.import_tasks: config.yml

# Perform whatever restarts are needed now, prevents double restart on first run
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure Mailman Core is enabled and running
  ansible.builtin.service:
    name: "{{ mailman3_core_service_name }}"
    enabled: true
    state: started
  when: mailman3_process_manager != "supervisor"
