---
- name: Install Nginx packages
  ansible.builtin.package:
    name: "nginx"
    state: present

- name: Create letsencrypt renewal dir
  ansible.builtin.file:
    dest: "/var/www/letsencrypt"
    state: directory
    mode: '0755'

- name: Copy nginx vhost
  ansible.builtin.template:
    src: templates/vhost.j2
    dest: /etc/nginx/sites-available/mailman-web
    mode: '0644'
  notify: Restart nginx

- name: Create link to the new config to enable it
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/mailman-web
    src: /etc/nginx/sites-available/mailman-web
    state: link
  notify: Restart nginx

- name: Remove default nginx vhost
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Install certbot
  community.general.snap:
    name: certbot
    classic: true
