---
- name: Apt update
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Set line in /etc/hosts
  when: mailman3_core_public_rest_api
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{ inventory_hostname }}"
    line: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }} {{ inventory_hostname }} {{ ansible_hostname }}"
    owner: root
    group: root
    mode: '0644'

- name: Set line in /etc/hosts 127.0.1.1
  when: not mailman3_core_public_rest_api
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{ inventory_hostname }}"
    line: "127.0.1.1 {{ inventory_hostname }} {{ ansible_hostname }}"
    owner: root
    group: root
    mode: '0644'
