---
# From https://stackoverflow.com/questions/24765930/add-swap-memory-with-ansible
- name: Configure swap
  when: swap_configure | bool | default(false)
  block:

    - name: Check if swap file exists
      ansible.builtin.stat:
        path: "{{ swap_file_path }}"
        get_checksum: false
        get_md5: false
        get_mime: false
        get_attributes: false
      register: swap_file_check
      changed_when: false

    - name: Check if swap is on
      ansible.builtin.shell:
        set -o pipefail;
        swapon --show | grep {{ swap_file_path }}
      args:
        executable: /bin/bash
      register: swap_enabled
      changed_when: false
      failed_when: false

    - name: Disable swap
      ansible.builtin.command: swapoff {{ swap_file_path }}
      register: swap_disabled
      changed_when: true
      when: >
        swap_file_check.stat.exists
        and swap_enabled.rc == 0
        and (not swap_enable
             or (swap_enable and swap_file_check.stat.size != (swap_file_size_mb * 1024 * 1024)))

    - name: Delete the swap file
      ansible.builtin.file:
        path: "{{ swap_file_path }}"
        state: absent
      when: not swap_enable

    - name: Configure swap
      when: swap_enable|bool
      block:

        - name: Create or change the size of swap file
          ansible.builtin.command: dd if=/dev/zero of={{ swap_file_path }} count={{ swap_file_size_mb }} bs=1MiB
          register: swap_file_created
          changed_when: true
          when: >
            not swap_file_check.stat.exists
            or swap_file_check.stat.size != (swap_file_size_mb * 1024 * 1024)

        - name: Change swap file permissions
          ansible.builtin.file:
            path: "{{ swap_file_path }}"
            owner: root
            group: root
            mode: '0600'

        - name: Check if swap is formatted
          ansible.builtin.shell:
            set -o pipefail;
            file {{ swap_file_path }} | grep 'swap file'
          args:
            executable: /bin/bash
          register: swap_file_is_formatted
          changed_when: false
          failed_when: false

        - name: Debugger1
          ansible.builtin.debug:
            var: swap_file_is_formatted

        - name: Debugger2
          ansible.builtin.debug:
            var: swap_file_created

        - name: Format swap file if it's not formatted
          ansible.builtin.command: mkswap {{ swap_file_path }}
          when: swap_file_is_formatted.rc > 0 or swap_file_created.changed
          changed_when: true

        - name: Add swap entry to fstab
          ansible.posix.mount:
            path: none
            src: "{{ swap_file_path }}"
            fstype: swap
            opts: defaults
            passno: 0
            dump: 0
            state: present

        - name: Turn on swap
          ansible.builtin.command: swapon -a
          when: swap_enable
          changed_when: false
          # original logic from article. However, let's start it every time.
          # when: swap_enabled.rc != 0 and swap_disabled.changed

        - name: Configure swappiness
          ansible.posix.sysctl:
            name: vm.swappiness
            value: "{{ swappiness }}"
            state: present
