---

- name: Reload systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: true

# invoke systemctl directly until someone implements https://github.com/ansible/ansible/issues/61763

- name: Restart mailman3-core service  # noqa command-instead-of-module
  ansible.builtin.command: systemctl try-restart {{ mailman3_core_service_name }}.service
  changed_when: false
  when:
    - mailman3_process_manager == "systemd"
    - ansible_virtualization_type != "docker"

- name: Restart mailman3-web service  # noqa command-instead-of-module
  ansible.builtin.command: systemctl try-restart {{ mailman3_web_service_name }}{{ '@' if mailman3_domains is defined else '' }}{{ item }}.service
  loop: "{{ mailman3_domains | default(['']) }}"
  changed_when: false
  when:
    - mailman3_process_manager == "systemd"
    - ansible_virtualization_type != "docker"

- name: Reload mailman3-web service  # noqa command-instead-of-module
  ansible.builtin.command: systemctl try-reload-or-restart {{ mailman3_web_service_name }}{{ '@' if mailman3_domains is defined else '' }}{{ item }}.service
  loop: "{{ mailman3_domains | default(['']) }}"
  changed_when: false
  when:
    - mailman3_process_manager == "systemd"
    - ansible_virtualization_type != "docker"

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Generate sasl_passwd.db
  ansible.builtin.command:
    cmd: postmap sasl_password
    chdir: /etc/postfix/sasl
  changed_when: always

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
