---

- name: Reload systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: true

# invoke systemctl directly until someone implements https://github.com/ansible/ansible/issues/61763

- name: Restart mailman3-core service  # noqa command-instead-of-module
  ansible.builtin.command: systemctl try-restart {{ mailman3_core_service_name }}.service
  changed_when: false
  when:
    - mailman3_process_manager == "systemd"
    - ansible_virtualization_type != "docker"

- name: Generate sasl_passwd.db
  ansible.builtin.command:
    cmd: postmap sasl_passwd
    chdir: /etc/postfix/sasl
  changed_when: true

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted
